### ISSUE TITLE
Cannot read property 'importKey' of undefined while creating message

### ISSUE THREAD

**Issue by stiivo** [cupcakearmy/cryptgeon#10]
Deployment via Docker:
```yml
version: '3.7'

services:
  memcached:
    image: memcached:1-alpine
    entrypoint: memcached -m 128 # Limit to 128 MB Ram, customize at free will.
    ports:
      - 11211:11211

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - memcached
    ports:
      - 8081:5000
```

> index.svelte-2cde6fd6.js:1 TypeError: Cannot read property 'importKey' of undefined
    at E (Button-93aec9d8.js:1)
    at HTMLFormElement.<anonymous> (index.svelte-2cde6fd6.js:1)
    at Generator.next (<anonymous>)
    at index.svelte-2cde6fd6.js:1
    at new Promise (<anonymous>)
    at a (index.svelte-2cde6fd6.js:1)
    at HTMLFormElement.<anonymous> (index.svelte-2cde6fd6.js:1)
    at HTMLFormElement.<anonymous> (vendor-cb0ac300.js:1)

Code: https://github.com/cupcakearmy/cryptgeon/blob/edbf8a8ecfd4652bd5fb092d53926882a93746a4/client/src/lib/crypto.ts#L29
