### ISSUE TITLE
Could not create a note please try again

### ISSUE THREAD

**Issue by pakyrs** [cupcakearmy/cryptgeon#113]
running it in docker, I am not greeted by this, altough it was working earlier on.

**Comment by cupcakearmy** [comment]
Can you share more notes on your setup?

**Comment by pakyrs** [comment]
Thanks Nicco, I used the default docker compose in the repo, running on a Bookworm VM.
SSL is via Let'sEncrypt on NGINX proxy manager.

I only added some Theming vars and changed the port to something free on my host.

Worked fine a couple of times freshly spawned then errored ever since. Tried on another two Docker servers and it's the same. I am thinking either NPM or the port I changed, but shouldn't be.

```
version: '3.8'

services:
  redis:
    container_name: redis-cryptgeon
    image: redis:7-alpine
    # Set a size limit. See link below on how to customise.
    # https://redis.io/docs/manual/eviction/
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru

  app:
    container_name: cryptgeon
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 4 MiB
      THEME_IMAGE: "path to my image CDN"
      THEME_TEXT: "TEST LINE
      THEME_PAGE_TITLE: "TEST"
      THEME_FAVICON: "path to my image CDN"
    ports:
      - 8099:8000

```
