### ISSUE TITLE
 cannot reach redis

### ISSUE THREAD

**Issue by cbin** [cupcakearmy/cryptgeon#126]
When trying to start a docker container I get this output:
```
Creating crypt_app_1 ... done
Creating crypt_proxy_1 ... done
Attaching to crypt_app_1, crypt_proxy_1
proxy_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
proxy_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
proxy_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
proxy_1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
app_1    | [2024-04-13T18:15:18Z ERROR cryptgeon] cannot reach redis
app_1    | thread 'main' panicked at 'canont reach redis', src/main.rs:28:9
app_1    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
proxy_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
proxy_1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
proxy_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
proxy_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
proxy_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
proxy_1  | 2024/04/13 18:15:18 [warn] 1#1: the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:15
proxy_1  | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /etc/nginx/conf.d/default.conf:15
crypt_app_1 exited with code 101
proxy_1  | 2024/04/13 18:15:18 [emerg] 1#1: host not found in upstream "app" in /etc/nginx/conf.d/default.conf:24
proxy_1  | nginx: [emerg] host not found in upstream "app" in /etc/nginx/conf.d/default.conf:24
crypt_proxy_1 exited with code 1
```
 docker-compose.yml

```
version: '3.8'

services:
  app:
    image: cupcakearmy/cryptgeon:latest
    environment:
      SIZE_LIMIT: 19 MiB
      #ALLOW_ADVANCED: false
     # THEME_PAGE_TITLE: "Note"
      REDIS: redis://default:*****@eu1-amusing*****:40111

  proxy:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
       - ./nginx-tls.conf:/etc/nginx/conf.d/default.conf
       - /home/user1/cert/fullchain.pem:/etc/nginx/conf.d/bundle.crt
       - /home/user1/cert/privkey.pem:/etc/nginx/conf.d/private.key
    ports:
      - 80:80
      - 443:443

```
