### ISSUE TITLE
Cryptgeon doesn't start after reboot

### ISSUE THREAD

**Issue by nicfab** [cupcakearmy/cryptgeon#139]
I set the `docker-compose.yml` as follows:

```
services:
  redis:
    image: redis:7-alpine

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis

    ports:
      - 8000:8000

    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 200 MiB
      THEME_IMAGE: "https://something"
      ALLOW_FILES: true
      THEME_PAGE_TITLE: "A title"
      THEME_FAVICON: "https://something"

    restart: always
```
I indicated here some ports, but I use different ones, and Cryptgeon works fine.
However, if the server is rebooted, Cryptgeon doesn't start, and I have to start it manually via `docker compose up -d`.
So, I added the last line `restart: always` to allow Cryptgeon to restart after a reboot.
However, I note from `watch docker ps` that it starts a loop going up and then restarts.
Where am I wrong?
How can I fix and allow Cryptegeon to start when the server starts?

**Comment by no8ody** [comment]
I'm not sure if it was because of this, but did you enable the docker service (e.g. for ubuntu systemctl enable docker)?

**Comment by nicfab** [comment]
I solved it by adding `restart: always` after each service, like below.

```
services:
  redis:
    image: redis:7-alpine
    restart: always

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    restart: always

    ports:
      - 8000:8000

    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 200 MiB
      THEME_IMAGE: "https://something"
      ALLOW_FILES: true
      THEME_PAGE_TITLE: "A title"
      THEME_FAVICON: "https://something"

```
