### ISSUE TITLE
Option for Autheticated Upload

### ISSUE THREAD

**Issue by MrCybertux** [cupcakearmy/cryptgeon#154]
Hello,

first i need to say thanks for that great piece of Software you wrote.
We use cryptgeon allmost on a daily base to share passwords or files.
We as a Team would like to have a higher upload limit for files.
For us it is clear that this is not something you can just ask of a open source service admin.
We would like to host our own service but restrict the usage to us Team members.
It does need to be fancy if there would be a own URI for note creation we can use HTTP basic auth.
So is there an option maybe to ask for a password bevor creating notes?
Or the Option to use a own URI for example: example.net/create ?

**Comment by mztiq** [comment]
+1.
I'd really like to see this as an option too.

**Comment by cupcakearmy** [comment]
The use case makes a lot of sense. However i would say this does not belong IN cryptgeon. However it's super easy to achieve.

```yaml
services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  redis:
    image: redis:7-alpine

  cryptgeon:
    image: cupcakearmy/cryptgeon
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cryptgeon.rule=Host(`cryptgeon.localhost`)"
      - "traefik.http.routers.cryptgeon.entrypoints=web"
      - "traefik.http.routers.cryptgeon.middlewares=cryptgeon-auth"
      - "traefik.http.middlewares.cryptgeon-auth.basicauth.users=user:$$2y$$05$$juUw0zgc5ebvJ00MFPVVLujF6P.rcEMbGZ99Jfq6ZWEa1dgetacEq"
```

```bash
docker compose up -d
```

1. Open http://cryptgeon.localhost
2. Log in with `user` and `secret`

More info on [traefik basic auth](https://doc.traefik.io/traefik/middlewares/http/basicauth/). This of course would work with different reverse proxies and auth methods. But i would delegate the task to other software that already does this better than i would ever implement :)

I'm happy to hear it's useful at your company ❤️ Especially in business context, donations are always welcome 🤗
Thanks for the input, will add it to the docs!
