### ISSUE TITLE
HTTP 404 Error with new version 1.4

### ISSUE THREAD

**Issue by canlot** [cupcakearmy/cryptgeon#27]
Hello,

with the new version i get a http 404 error when i create a new note.
1.3 version works but not the 1.4.

![image](https://user-images.githubusercontent.com/7008555/157453913-967b7178-13c7-47eb-a270-498080f48419.png)

I tried to debug it, but cannot find the settings to turn logging on.

My docker-compose file:

```
version: '3.7'

services:
  memcached:
    container_name: memcached_cryptgeon
    image: memcached:1-alpine
    restart: unless-stopped
    entrypoint: memcached -m 256M
    ports:
      - 11211:11211

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - memcached
    environment:
      SIZE_LIMIT: 10M
    ports:
      - 80:5000
```
