### ISSUE TITLE
Cannot create notes

### ISSUE THREAD

**Issue by Vexz00** [cupcakearmy/cryptgeon#51]
I run cryptgeon (latest version) inside Docker on my NAS at home and it worked flawlessly in the past. I haven't used it for a while but now when I try to create a new note a red message appears in the top right corner that the note couldn't be created.

The only thing Portainer shows in the logs is the following:
`No log line matching the '' filter`

Here's the stack I used to create the container.
```
version: '3.7'

services:
  memcached:
    container_name: Cryptgeon_Memcached
    image: memcached
    entrypoint: memcached -m 512M -I 64M

  app:
    container_name: Cryptgeon
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - memcached
    environment:
      SIZE_LIMIT: 64M
    ports:
      - 8120:5000
```

Is there any more information I can provide to look into the problem here?

**Comment by cupcakearmy** [comment]
Version 2 uses redis and not memcached now.
Either pin version 1 with `cupcakearmy/cryptgeon:1` or update to `cupcakearmy/cryptgeon:2` and use redis instead of memcache :) All the updated configs are in the readme :)

If you still have troubles feel free to reopen

**Comment by Vexz00** [comment]
Ah! Good to know. I just updated my stack according to the readme and it's working again. Thank you very much!

**Comment by twixwix** [comment]
I have all the time the note in the upper right corner "can't create note. please try again". Is there anywhere a log or something else? 

```
version: '3.7'
services: 
 redis:
  image: redis:7-alpine

 cryptgeon:
  image: cupcakearmy/cryptgeon:2
  depends_on:
    - redis
  environment:
    SIZE_LIMIT: 4 MiB
  ports:
    - 5000:5000
```

**Comment by cupcakearmy** [comment]
could you run (just to be sure):
```sh
docker compose down
docker compose pull
docker compose up
```

Is there anything in `docker compose logs -f` then?

**Comment by geoigeek** [comment]
I have the same Issue. Docker runs on Ubuntu LXC on Proxmox. Same Problem on a Hetzner Ubuntu VM.

docker-compose.yml
```
version: '3.8'

services:
  redis:
    image: redis:7-alpine

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    environment:
      SIZE_LIMIT: 4 MiB
    ports:
      - 85:5000

```

Here is my docker compose log

```
redis_1  | 1:C 27 Sep 2022 19:50:59.788 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 27 Sep 2022 19:50:59.788 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 27 Sep 2022 19:50:59.788 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 27 Sep 2022 19:50:59.788 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 27 Sep 2022 19:50:59.790 * Running mode=standalone, port=6379.
redis_1  | 1:M 27 Sep 2022 19:50:59.790 # Server initialized
redis_1  | 1:M 27 Sep 2022 19:50:59.790 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 27 Sep 2022 19:50:59.790 * Ready to accept connections
```
