### ISSUE TITLE
Cannot create notes

### ISSUE THREAD

**Issue by geoigeek** [cupcakearmy/cryptgeon#59]
I have the same Issue. Docker runs on Ubuntu LXC on Proxmox. Same Problem on a Hetzner Ubuntu VM.

docker-compose.yml
```
version: '3.8'

services:
  redis:
    image: redis:7-alpine

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    environment:
      SIZE_LIMIT: 4 MiB
    ports:
      - 85:5000

```

Here is my docker compose log

```
redis_1  | 1:C 27 Sep 2022 19:50:59.788 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 27 Sep 2022 19:50:59.788 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 27 Sep 2022 19:50:59.788 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 27 Sep 2022 19:50:59.788 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 27 Sep 2022 19:50:59.790 * Running mode=standalone, port=6379.
redis_1  | 1:M 27 Sep 2022 19:50:59.790 # Server initialized
redis_1  | 1:M 27 Sep 2022 19:50:59.790 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 27 Sep 2022 19:50:59.790 * Ready to accept connections
```

_Originally posted by @geoigeek in https://github.com/cupcakearmy/cryptgeon/issues/51#issuecomment-1259987329_

**Comment by cupcakearmy** [comment]
Are there any logs? Either in the client console or in the backend?

**Comment by geoigeek** [comment]
here the Client console Logs:
```
XHRPOSThttps://crypt.domain.tld/api/notes/[HTTP/2 500 Internal Server Error 5125ms]
	•	



POST
https://crypt.domain.tld/api/notes/
Status
500
Internal Server Error
VersionHTTP/2
Übertragen202 B (26 B Größe)
Referrer Policystrict-origin-when-cross-origin
	•	


content-encoding
gzip

date
Sun, 02 Oct 2022 10:16:06 GMT
server
openresty
vary
accept-encoding

X-Firefox-Spdy
h2



Accept
*/*
Accept-Encoding
gzip, deflate, br
Accept-Language
de,en-US;q=0.7,en;q=0.3
Connection
keep-alive
Content-Length
189
Content-Type
application/json
DNT
1
Host
crypt.domain.tld
Origin
https://crypt.domain.tld
Referer
https://crypt.domain.tld/
Sec-Fetch-Dest
empty
Sec-Fetch-Mode
cors
Sec-Fetch-Site
same-origin
Sec-GPC
1
TE
trailers
User-Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0
Error: API call failed
    Immutable 4
index.svelte-f0c77b64.js:1:22716
```

**Comment by cupcakearmy** [comment]
I suppose the server logs are empty? I'll be back on the 6th, so will have a look then

**Comment by geoigeek** [comment]
# docker-compose logs
Attaching to cryptgen_app_1, cryptgen_redis_1
redis_1  | 1:C 02 Oct 2022 12:46:42.292 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1  | 1:C 02 Oct 2022 12:46:42.292 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1  | 1:C 02 Oct 2022 12:46:42.292 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1  | 1:M 02 Oct 2022 12:46:42.293 * monotonic clock: POSIX clock_gettime
redis_1  | 1:M 02 Oct 2022 12:46:42.294 * Running mode=standalone, port=6379.
redis_1  | 1:M 02 Oct 2022 12:46:42.294 # Server initialized
redis_1  | 1:M 02 Oct 2022 12:46:42.295 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1  | 1:M 02 Oct 2022 12:46:42.295 * Ready to accept connections

**Comment by cupcakearmy** [comment]
Mhh, that's only redis. Def should add some logging for 500 errors. I kept logging to the most minimum for now

**Comment by cupcakearmy** [comment]
Can you try using the verion `2.0.3` and setting `VERBOSITY=debug`?

**Comment by PaoloTK** [comment]
I'm also experiencing the same problem. As a matter of fact, I deployed Cryptgeon a long time ago and was never able to generate notes, but had little time to troubleshoot. This is my current docker-compose configuration:

```
  cryptgeon:
    container_name: cryptgeon
    depends_on:
      - redis
    environment:
      SIZE_LIMIT: 4 MiB
      VERBOSITY: debug
    image: cupcakearmy/cryptgeon:latest
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.cryptgeon-rtr.entrypoints=https"
      - "traefik.http.routers.cryptgeon-rtr.rule=Host(`notes.$DOMAINNAME`)"
      - "traefik.http.routers.cryptgeon-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.cryptgeon-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.cryptgeon-rtr.service=cryptgeon-svc"
      - "traefik.http.services.cryptgeon-svc.loadbalancer.server.port=5000"
    networks:
      - traefik
    ports:
    - 5000:5000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

When I generate a note I get the error:

> could not create note. please try again

The only entry in the log for cryptgeon when I hit "create" is the following:

> actix_web::middleware::logger] "POST /api/notes/ HTTP/1.1" 500 26 0.001640

Nothing happens on the redis logs.
