### ISSUE TITLE
Already have NPM, want to load on https://example.com/note - blank screen

### ISSUE THREAD

**Issue by shayaknyc** [cupcakearmy/cryptgeon#67]
Hey y'all - forgive me as I'm relatively new to reverse proxies, etc. I've been looking for self-hosted alternative to privnote, and the internet said this is the best one! LOL So, I'm trying it out. I'm able to load it locally over http but obviously it won't encrypt since the note on the README indicates cryptographic functions only work over https. I already have NGINX Proxy Manager and I already have a subdomain I'd like to use. In NPM, I have set up a custom location for the subdomain:
`sub.example.com/note`

Under this custom location, I indicated the IP and Port I configured in docker-compose.yml and then used the parameters included in `examples/nginx/nginx-plain.conf` and added these:
```
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

However, when I load https://sub.example.com/note - I'm met with a blank screen. Here's a copy of my `docker-compose.yml` file:
```
version: '3.8'

services:
  redis_cryptgeon:
    image: redis:7-alpine
    # Set a size limit. See link below on how to customise.
    # https://redis.io/docs/manual/eviction/
    # command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis_cryptgeon
    environment:
      # Size limit for a single note.
      SIZE_LIMIT: 4 MiB
      VERBOSITY: debug
    ports:
      - 5080:5000
```
Here's a copy of the debug log:
```
cryptgeon-app-1              | [2022-11-15T16:11:47Z INFO  actix_server::builder] Starting 12 workers
cryptgeon-app-1              | [2022-11-15T16:11:47Z INFO  actix_server::server] Actix runtime found; starting in Actix runtime
cryptgeon-redis_cryptgeon-1  | 1:C 15 Nov 2022 16:11:47.283 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cryptgeon-redis_cryptgeon-1  | 1:C 15 Nov 2022 16:11:47.283 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
cryptgeon-redis_cryptgeon-1  | 1:C 15 Nov 2022 16:11:47.283 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cryptgeon-redis_cryptgeon-1  | 1:M 15 Nov 2022 16:11:47.283 * monotonic clock: POSIX clock_gettime
cryptgeon-redis_cryptgeon-1  | 1:M 15 Nov 2022 16:11:47.284 * Running mode=standalone, port=6379.
cryptgeon-redis_cryptgeon-1  | 1:M 15 Nov 2022 16:11:47.284 # Server initialized
cryptgeon-redis_cryptgeon-1  | 1:M 15 Nov 2022 16:11:47.284 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cryptgeon-redis_cryptgeon-1  | 1:M 15 Nov 2022 16:11:47.284 * Ready to accept connections
cryptgeon-app-1              | [2022-11-15T16:16:41Z DEBUG actix_files::service] error handling /note: No such file or directory (os error 2)
cryptgeon-app-1              | [2022-11-15T16:16:41Z INFO  actix_web::middleware::logger] "GET /note HTTP/1.1" 200 898 0.000643
```

It seems it's also trying to load `/note` on the container, which obviously doesn't exist. I'm not entirely sure how to make it load on a sub-directory in the URL which already includes a subdomain. Otherwise, I'd just create a new subdomain such as `note.example.com` and just have it load that way, but unfortunately, I'm unable to add a new subdomain. Any ideas/help on how to get this to load properly? I'm sure I'm missing something, but I don't know how to properly phrase the search terms to get what I'm trying to do....
