### ISSUE TITLE
Version 2.2 does not work with docker - x86

### ISSUE THREAD

**Issue by RainrZufall** [cupcakearmy/cryptgeon#74]
Hi,

the new version 2.2 seems to cause problems with docker.
Unfortunately, there are no logs that i can provide.

if I set the version to "2.1" in my cocker-compose.yml, everything works as expected again.

my yaml
```
version: '3'

services:
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 1GiB
    networks: [cryptgeon]

  app:
    container_name: cryptgeon
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    environment:
      SIZE_LIMIT: 50MiB
    ports:
      - 5000:5000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    networks: [cryptgeon]

networks:
    cryptgeon:
        external: true
```
