### ISSUE TITLE
Not able to retrieve files 25MB or more

### ISSUE THREAD

**Issue by johnnyq** [cupcakearmy/cryptgeon#80]
We are using the docker compose with Traefik example you have with a File Limit set to 500 MiB. We can upload a 25MB or greater file we just cannot retrieve the 25MB or larger file

When retrieving the file and clicking on view note we get this message

**wrong password. could not decipher. probably a broken link. note was destroyed.**

Anything below 25MB we can retrieve with no problem

Is there another limit somewhere we are missing?

**Comment by cupcakearmy** [comment]
Could you share the config?

**Comment by angelfor3v3r** [comment]
> Could you share the config?

I'm getting the same issue.

I've uploaded a 27MB file and I get a `wrong password. could not decipher. probably a broken link. note was destroyed.` when I try to download it from the note. Smaller sizes seem to work fine, I'm going to guess it's around the 25 MiB mark.

Could it perhaps be a browser/Traefik configuration issue as well? Just throwing out ideas.

I also noticed that even though I have `SIZE_LIMIT: 50 MiB` set in my Docker Compose config, the site renders the max size incorrectly as `max: 37 MiB`. Could this also be related somehow? It seems to happen with any size I set and displays an incorrect size.

Anyway. Here's my configuration and I'm running Traefik in front of it.
```yaml
cryptgeon-redis:
    image: redis:7-alpine
    restart: unless-stopped
    container_name: cryptgeon-redis
    networks: [internal]
    volumes:
        - /docker/site/cryptgeon/redis:/data
    command: redis-server --maxmemory 8gb --maxmemory-policy allkeys-lru
cryptgeon:
    image: cupcakearmy/cryptgeon:latest
    restart: unless-stopped
    container_name: cryptgeon
    networks: [internal, public]
    environment:
        REDIS: redis://cryptgeon-redis/
        SIZE_LIMIT: 50 MiB
        MAX_VIEWS: 100
        MAX_EXPIRATION: 1440
        ALLOW_ADVANCED: true
        ID_LENGTH: 32
        VERBOSITY: warn
```

I apologize if I've configured something incorrectly, I just set this up tonight on my host. I will say, it was really easy to set up. The only other complaint I have is the documentation for setting up Traefik seems to be very scattered and inconsistent. The Github repo and Docker hub pages seem to give different instructions, but thats unrelated to this issue.
